/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Jwks {
  createdAt: Timestamp;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface StratifyAssetPrices {
  assetId: string;
  closePrice: Numeric;
  countryId: number;
  createdAt: Generated<Timestamp>;
  highPrice: Numeric;
  lowPrice: Numeric;
  openPrice: Numeric;
  priceDate: Timestamp;
  volume: Numeric;
}

export interface StratifyAssets {
  countryId: number;
  createdAt: Generated<Timestamp>;
  name: string;
  symbol: string;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface StratifyCountries {
  alpha2: string;
  alpha3: string;
  createdAt: Generated<Timestamp>;
  currency: string;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface StratifyCurrencies {
  code: string;
  name: string;
}

export interface StratifyMigrationsDbMigrations {
  name: string;
  timestamp: string;
}

export interface TwoFactor {
  backupCodes: string;
  id: string;
  secret: string;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  twoFactorEnabled: boolean | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  jwks: Jwks;
  session: Session;
  "stratify.assetPrices": StratifyAssetPrices;
  "stratify.assets": StratifyAssets;
  "stratify.countries": StratifyCountries;
  "stratify.currencies": StratifyCurrencies;
  "stratifyMigrations.dbMigrations": StratifyMigrationsDbMigrations;
  twoFactor: TwoFactor;
  user: User;
  verification: Verification;
}
