/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Countries {
    code: string;
    createdAt: Generated<Timestamp>;
    currency: string;
    id: Generated<number>;
    name: string;
    threeLetterCode: string;
    updatedAt: Generated<Timestamp>;
}

export interface Stocks {
    countryId: number;
    createdAt: Generated<Timestamp>;
    name: string;
    symbol: string;
    type: string;
    updatedAt: Generated<Timestamp>;
}

export interface StratifyMigrationsDbMigrations {
    name: string;
    timestamp: string;
}

export interface DB {
    countries: Countries;
    stocks: Stocks;
    "stratifyMigrations.dbMigrations": StratifyMigrationsDbMigrations;
}
