mock_yfinance_fund_data = {
    "shortName": "S&P 500 ETF fund",
    "longName": "Standard & Poorer 500 ETF Fund",
    "symbol": "SP500",
    "quoteType": "ETF",
    "fundFamily": "S&P",
    "marketState": "REGULAR",
    "currency": "USD",
    "fullExchangeName": "A stock exchange",
    "exchangeTimezoneShortName": "EST",
    "regularMarketPrice": 450.25,
    "regularMarketOpen": 448.00,
    "regularMarketDayHigh": 452.00,
    "regularMarketDayLow": 447.50,
    "regularMarketPreviousClose": 449.00,
    "regularMarketVolume": 1200000,
    "regularMarketChange": 1.25,
    "regularMarketChangePercent": 0.28,
}