mock_yfinance_crypto_data = {
    "name": "Bitcoin",
    "symbol": "BTC-USD",
    "description": "Bitcoin is a digital currency",
    "fromCurrency": "BTC",
    "currency": "USD",
    "marketCap": 1000000000,
    "marketState": "REGULAR",
    "allTimeHigh": 150000,
    "allTimeLow": 10,
    "regularMarketPrice": 45000,
    "regularMarketOpen": 44000,
    "regularMarketDayHigh": 46000,
    "regularMarketDayLow": 43000,
    "regularMarketPreviousClose": 44500,
    "regularMarketVolume": 35000,
    "regularMarketChange": 500,
    "regularMarketChangePercent": 1.12,
}