const startOfMonthDate = (monthsAgo: number) => {
    const date = new Date();
    date.setMonth(date.getMonth() - monthsAgo, 1);

    const isWeekend = date.getDay() === 0 || date.getDay() === 6;

    if (isWeekend) {
        date.setDate(date.getDay() === 0 ? 2 : 3);
    }

    return date;
};

const endOfMonthDate = (monthsAgo: number) => {
    const date = new Date();
    date.setMonth(date.getMonth() - monthsAgo + 1, 0);

    const isWeekend = date.getDay() === 0 || date.getDay() === 6;

    if (isWeekend) {
        date.setDate(date.getDate() - (date.getDay() === 0 ? 2 : 1));
    }

    return date;
};

export const mockHistoricAssetPrices = [
    {
        assetId: 1,
        priceDate: startOfMonthDate(1),
        lowPrice: 148,
        highPrice: 156,
        openPrice: 150,
        closePrice: 152,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(1),
        lowPrice: 150,
        highPrice: 158,
        openPrice: 152,
        closePrice: 155,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(2),
        lowPrice: 143,
        highPrice: 151,
        openPrice: 145,
        closePrice: 148,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(2),
        lowPrice: 146,
        highPrice: 154,
        openPrice: 148,
        closePrice: 150,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(3),
        lowPrice: 139,
        highPrice: 147,
        openPrice: 141,
        closePrice: 143,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(3),
        lowPrice: 141,
        highPrice: 149,
        openPrice: 143,
        closePrice: 145,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(4),
        lowPrice: 135,
        highPrice: 143,
        openPrice: 137,
        closePrice: 139,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(4),
        lowPrice: 137,
        highPrice: 145,
        openPrice: 139,
        closePrice: 141,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(5),
        lowPrice: 130,
        highPrice: 138,
        openPrice: 132,
        closePrice: 135,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(5),
        lowPrice: 133,
        highPrice: 141,
        openPrice: 135,
        closePrice: 137,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(6),
        lowPrice: 126,
        highPrice: 134,
        openPrice: 128,
        closePrice: 130,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(6),
        lowPrice: 128,
        highPrice: 136,
        openPrice: 130,
        closePrice: 132,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(7),
        lowPrice: 121,
        highPrice: 129,
        openPrice: 123,
        closePrice: 126,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(7),
        lowPrice: 124,
        highPrice: 132,
        openPrice: 126,
        closePrice: 128,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(8),
        lowPrice: 117,
        highPrice: 125,
        openPrice: 119,
        closePrice: 121,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(8),
        lowPrice: 119,
        highPrice: 127,
        openPrice: 121,
        closePrice: 123,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(9),
        lowPrice: 113,
        highPrice: 121,
        openPrice: 115,
        closePrice: 117,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(9),
        lowPrice: 115,
        highPrice: 123,
        openPrice: 117,
        closePrice: 119,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(10),
        lowPrice: 109,
        highPrice: 117,
        openPrice: 111,
        closePrice: 113,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(10),
        lowPrice: 111,
        highPrice: 119,
        openPrice: 113,
        closePrice: 115,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(11),
        lowPrice: 105,
        highPrice: 113,
        openPrice: 107,
        closePrice: 109,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(11),
        lowPrice: 107,
        highPrice: 115,
        openPrice: 109,
        closePrice: 111,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(12),
        lowPrice: 101,
        highPrice: 109,
        openPrice: 103,
        closePrice: 105,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(12),
        lowPrice: 103,
        highPrice: 111,
        openPrice: 105,
        closePrice: 107,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(13),
        lowPrice: 97,
        highPrice: 105,
        openPrice: 99,
        closePrice: 101,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(13),
        lowPrice: 99,
        highPrice: 107,
        openPrice: 101,
        closePrice: 103,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(14),
        lowPrice: 93,
        highPrice: 101,
        openPrice: 95,
        closePrice: 97,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(14),
        lowPrice: 95,
        highPrice: 103,
        openPrice: 97,
        closePrice: 99,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(15),
        lowPrice: 90,
        highPrice: 98,
        openPrice: 92,
        closePrice: 94,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(15),
        lowPrice: 92,
        highPrice: 100,
        openPrice: 94,
        closePrice: 95,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(16),
        lowPrice: 87,
        highPrice: 95,
        openPrice: 89,
        closePrice: 91,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(16),
        lowPrice: 89,
        highPrice: 97,
        openPrice: 91,
        closePrice: 92,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(17),
        lowPrice: 84,
        highPrice: 92,
        openPrice: 86,
        closePrice: 88,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(17),
        lowPrice: 86,
        highPrice: 94,
        openPrice: 88,
        closePrice: 89,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(18),
        lowPrice: 81,
        highPrice: 89,
        openPrice: 83,
        closePrice: 85,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(18),
        lowPrice: 83,
        highPrice: 91,
        openPrice: 85,
        closePrice: 86,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(19),
        lowPrice: 79,
        highPrice: 87,
        openPrice: 81,
        closePrice: 82,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(19),
        lowPrice: 80,
        highPrice: 88,
        openPrice: 82,
        closePrice: 83,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(20),
        lowPrice: 77,
        highPrice: 85,
        openPrice: 79,
        closePrice: 80,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(20),
        lowPrice: 78,
        highPrice: 86,
        openPrice: 80,
        closePrice: 81,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(21),
        lowPrice: 74,
        highPrice: 82,
        openPrice: 76,
        closePrice: 77,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(21),
        lowPrice: 75,
        highPrice: 83,
        openPrice: 77,
        closePrice: 79,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(22),
        lowPrice: 71,
        highPrice: 79,
        openPrice: 73,
        closePrice: 74,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(22),
        lowPrice: 72,
        highPrice: 80,
        openPrice: 74,
        closePrice: 76,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(23),
        lowPrice: 69,
        highPrice: 77,
        openPrice: 71,
        closePrice: 72,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(23),
        lowPrice: 70,
        highPrice: 78,
        openPrice: 72,
        closePrice: 73,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(24),
        lowPrice: 66,
        highPrice: 74,
        openPrice: 68,
        closePrice: 69,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(24),
        lowPrice: 67,
        highPrice: 75,
        openPrice: 69,
        closePrice: 71,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(25),
        lowPrice: 63,
        highPrice: 71,
        openPrice: 65,
        closePrice: 66,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(25),
        lowPrice: 64,
        highPrice: 72,
        openPrice: 66,
        closePrice: 68,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(26),
        lowPrice: 61,
        highPrice: 69,
        openPrice: 63,
        closePrice: 64,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(26),
        lowPrice: 62,
        highPrice: 70,
        openPrice: 64,
        closePrice: 65,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(27),
        lowPrice: 58,
        highPrice: 66,
        openPrice: 60,
        closePrice: 61,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(27),
        lowPrice: 59,
        highPrice: 67,
        openPrice: 61,
        closePrice: 63,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(28),
        lowPrice: 56,
        highPrice: 64,
        openPrice: 58,
        closePrice: 59,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(28),
        lowPrice: 57,
        highPrice: 65,
        openPrice: 59,
        closePrice: 60,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(29),
        lowPrice: 53,
        highPrice: 61,
        openPrice: 55,
        closePrice: 56,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(29),
        lowPrice: 54,
        highPrice: 62,
        openPrice: 56,
        closePrice: 58,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(30),
        lowPrice: 51,
        highPrice: 59,
        openPrice: 53,
        closePrice: 54,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(30),
        lowPrice: 52,
        highPrice: 60,
        openPrice: 54,
        closePrice: 55,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(31),
        lowPrice: 49,
        highPrice: 57,
        openPrice: 51,
        closePrice: 52,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(31),
        lowPrice: 50,
        highPrice: 58,
        openPrice: 52,
        closePrice: 53,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(32),
        lowPrice: 47,
        highPrice: 55,
        openPrice: 49,
        closePrice: 50,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(32),
        lowPrice: 48,
        highPrice: 56,
        openPrice: 50,
        closePrice: 51,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(33),
        lowPrice: 44,
        highPrice: 52,
        openPrice: 46,
        closePrice: 47,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(33),
        lowPrice: 45,
        highPrice: 53,
        openPrice: 47,
        closePrice: 49,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(34),
        lowPrice: 42,
        highPrice: 50,
        openPrice: 44,
        closePrice: 45,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(34),
        lowPrice: 43,
        highPrice: 51,
        openPrice: 45,
        closePrice: 46,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(35),
        lowPrice: 40,
        highPrice: 48,
        openPrice: 42,
        closePrice: 43,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(35),
        lowPrice: 41,
        highPrice: 49,
        openPrice: 43,
        closePrice: 44,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: startOfMonthDate(36),
        lowPrice: 38,
        highPrice: 46,
        openPrice: 40,
        closePrice: 41,
        volume: 1000,
    },
    {
        assetId: 1,
        priceDate: endOfMonthDate(36),
        lowPrice: 39,
        highPrice: 47,
        openPrice: 41,
        closePrice: 42,
        volume: 1000,
    },
];
