[project]
name = "stratify-data-api"
version = "0.1.0"
description = "A REST API for accessing stock market data powered by Yahoo Finance and Stooq."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "yfinance>=0.2.65",
]
