mock_yfinance_ticker_data = {
    "symbol": "AAPL",
    "displayName": "Apple Inc.",
    "shortName": "Apple",
    "longName": "Apple Inc.",
    "longBusinessSummary": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
    "marketState": "REGULAR",
    "marketCap": 3000000000000,
    "industry": "Consumer Electronics",
    "sector": "Technology",
    "quoteType": "EQUITY",
    "regularMarketPrice": 150.25,
    "regularMarketOpen": 149.00,
    "regularMarketDayHigh": 151.00,
    "regularMarketDayLow": 148.75,
    "regularMarketPreviousClose": 150.00,
    "regularMarketVolume": 75000000,
    "regularMarketChange": 1.75,
    "regularMarketChangePercent": 1.18,
}
