name: Detect Changes

on:
    workflow_call:
        outputs:
            stratify-data-api:
                value: ${{ jobs.detect-changes.outputs.stratify-data-api || 'false' }}

jobs:
    detect-changes:
        name: Detect Changes
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: read
        outputs:
            stratify-data-api: ${{ steps.filter.outputs.stratify-data-api }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Detect changed package(s)
              id: filter
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      stratify-data-api:
                        - 'apps/api/stratify-data-api/**'
