name: Docker Image Checks

# Only run workflow on main after successful build
on:
    workflow_run:
        workflows: [Build]
        types: completed
        branches: main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    stratify-api:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build @stratify/stratify-api Docker image
              run: docker build -f apps/api/stratify-api/Dockerfile . -t stratify-api:ci

    stratify-data-api:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build @stratify/stratify-data-api Docker image
              run: docker build -f apps/api/stratify-data-api/Dockerfile . -t stratify-data-api:ci

    stratify-ui:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build @stratify/stratify-ui Docker image
              run: docker build --no-cache -f apps/ui/stratify-ui/Dockerfile . -t stratify-ui:ci
