name: Push Docker Image(s) to GHCR

on:
  workflow_run:
    workflows: [Update Package Version]
    types: completed

jobs:
  #? This is required to detect which apps have changes so that Docker images are only built and pushed for those
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      stratify-data-api: ${{ steps.filter.outputs.stratify-data-api }}
      stratify-api: ${{ steps.filter.outputs.stratify-api }}
      stratify-ui: ${{ steps.filter.outputs.stratify-ui }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine commit range for detecting changes
        id: commit_range
        run: |
          echo "BASE_COMMIT=$(git rev-parse HEAD~2)" >> "$GITHUB_OUTPUT"
          echo "REF_COMMIT=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"

      - name: Detect changed package(s)
        id: filter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_COMMIT: ${{ steps.commit_range.outputs.BASE_COMMIT }}
          REF_COMMIT: ${{ steps.commit_range.outputs.REF_COMMIT }}
        uses: dorny/paths-filter@v3
        with:
          base: ${{ env.BASE_COMMIT }}
          ref: ${{ env.REF_COMMIT }}
          filters: |
            stratify-data-api:
              - 'apps/api/stratify-data-api/**'
            stratify-api:
              - 'apps/api/stratify-api/**'
            stratify-ui:
              - 'apps/ui/stratify-ui/**'

  stratify-api:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.stratify-api == 'true' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get package version
        id: package-version
        run: echo "VERSION=$(jq -r .version apps/api/stratify-api/package.json)" >> "$GITHUB_OUTPUT"

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/stratify-api/Dockerfile
          push: true
          tags: ghcr.io/kishanj22/stratify/stratify-api:${{ steps.package-version.outputs.VERSION }}

  stratify-data-api:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.stratify-data-api == 'true' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get package version
        id: package-version
        run: echo "VERSION=$(jq -r .version apps/api/stratify-data-api/package.json)" >> "$GITHUB_OUTPUT"

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/stratify-data-api/Dockerfile
          push: true
          tags: ghcr.io/kishanj22/stratify/stratify-data-api:${{ steps.package-version.outputs.VERSION }}

  stratify-ui:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.stratify-ui == 'true' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Output message for manual run
        run: |
          echo "### Stratify UI Docker Image" >> $GITHUB_STEP_SUMMARY
          echo "The Stratify UI Docker image must be built and pushed manually using the next-ghcr-push workflow" >> $GITHUB_STEP_SUMMARY
