name: Deploy to Production Environment

on:
    workflow_dispatch:
        inputs:
            release_tag:
                description: Release tag to deploy (e.g. release-05-04-2026.1)
                required: true
                type: string

jobs:
    prepare-deployment:
        name: Prepare Deployment
        runs-on: self-hosted
        outputs:
            release-tag: ${{ steps.get_release_manifest.outputs.release_tag }}
            stratify_data_api_version: ${{ steps.get_release_manifest.outputs.stratify_data_api_version }}
            is_stratify_data_api_changed: ${{ steps.get_release_manifest.outputs.is_stratify_data_api_changed }}
            stratify_api_version: ${{ steps.get_release_manifest.outputs.stratify_api_version }}
            is_stratify_api_changed: ${{ steps.get_release_manifest.outputs.is_stratify_api_changed }}
            stratify_ui_version: ${{ steps.get_release_manifest.outputs.stratify_ui_version }}
            is_stratify_ui_changed: ${{ steps.get_release_manifest.outputs.is_stratify_ui_changed }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get release manifest from specified release
              id: get_release_manifest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ inputs.release_tag }}
              run: |
                  #? Get the release manifest from the specified release tag
                  release=$(gh release view "$RELEASE_TAG" --repo "$GITHUB_REPOSITORY" --json tagName,body -q '.body')
                  release_json=$(echo $release | jq -r '.')

                  release_tag=$(echo "$release_json" | jq -r '.releaseTag')
                  release_apps=$(echo "$release_json" | jq -r '.apps')

                  stratify_data_api_version=$(echo "$release_apps" | jq -r '.["stratify-data-api"].version')
                  is_stratify_data_api_changed=$(echo "$release_apps" | jq -r '.["stratify-data-api"].isChanged')

                  stratify_api_version=$(echo "$release_apps" | jq -r '.["stratify-api"].version')
                  is_stratify_api_changed=$(echo "$release_apps" | jq -r '.["stratify-api"].isChanged')

                  stratify_ui_version=$(echo "$release_apps" | jq -r '.["stratify-ui"].version')
                  is_stratify_ui_changed=$(echo "$release_apps" | jq -r '.["stratify-ui"].isChanged')

                  echo "release_tag=$release_tag" >> "$GITHUB_OUTPUT"
                  echo "stratify_data_api_version=$stratify_data_api_version" >> "$GITHUB_OUTPUT"
                  echo "is_stratify_data_api_changed=$is_stratify_data_api_changed" >> "$GITHUB_OUTPUT"
                  echo "stratify_api_version=$stratify_api_version" >> "$GITHUB_OUTPUT"
                  echo "is_stratify_api_changed=$is_stratify_api_changed" >> "$GITHUB_OUTPUT"
                  echo "stratify_ui_version=$stratify_ui_version" >> "$GITHUB_OUTPUT"
                  echo "is_stratify_ui_changed=$is_stratify_ui_changed" >> "$GITHUB_OUTPUT"

    deploy-stratify-data-api:
        name: Deploy Stratify Data API
        runs-on: self-hosted
        needs: prepare-deployment
        if: ${{ needs.prepare-deployment.outputs.is_stratify_data_api_changed == 'true' }}
        environment: Production
        permissions:
            contents: read
            packages: read
        steps:
            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Check if image exists in GHCR
              id: image_check
              run: |
                  IMAGE_NAME="ghcr.io/kishanj22/stratify/stratify-data-api:${{ needs.prepare-deployment.outputs.stratify_data_api_version }}"
                  echo "Checking if image exists: $IMAGE_NAME"

                  if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
                      echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
                      echo "Image exists: $IMAGE_NAME"
                  else
                      echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
                      echo "Image does not exist: $IMAGE_NAME"
                      exit 1
                  fi

            #? API calls have to be made here instead of the Coolify CLI as the CLI returns a 401 unauthorized error
            - name: Update Stratify Data API in Coolify
              run: |
                  curl -X PATCH "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_DATA_API_UUID }}" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      -d `{
                          "docker_registry_image_tag": "${{ needs.prepare-deployment.outputs.stratify_data_api_version }}",
                          "description": "${{ needs.prepare-deployment.outputs.release-tag }}"    
                      }`

            - name: Restart Stratify Data API in Coolify
              run: |
                  curl -X GET "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_DATA_API_UUID }}/restart" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json"

    deploy-stratify-api:
        name: Deploy Stratify API
        runs-on: self-hosted
        needs: [prepare-deployment, deploy-stratify-data-api]
        if: ${{ always() && needs.prepare-deployment.outputs.is_stratify_api_changed == 'true' && needs.deploy-stratify-data-api.result != 'failure' }}
        environment: Production
        permissions:
            contents: read
            packages: read
        steps:
            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Check if image exists in GHCR
              id: image_check
              run: |
                  IMAGE_NAME="ghcr.io/kishanj22/stratify/stratify-api:${{ needs.prepare-deployment.outputs.stratify_api_version }}"
                  echo "Checking if image exists: $IMAGE_NAME"

                  if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
                      echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
                      echo "Image exists: $IMAGE_NAME"
                  else
                      echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
                      echo "Image does not exist: $IMAGE_NAME"
                      exit 1
                  fi

            - name: Update Stratify API in Coolify
              run: |
                  curl -X PATCH "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_API_UUID }}" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      -d `{
                          "docker_registry_image_tag": "${{ needs.prepare-deployment.outputs.stratify_api_version }}",
                          "description": "${{ needs.prepare-deployment.outputs.release-tag }}"    
                      }`

            - name: Restart Stratify API in Coolify
              run: |
                  curl -X GET "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_API_UUID }}/restart" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json"

    deploy-stratify-ui:
        name: Deploy Stratify UI
        runs-on: self-hosted
        needs: [prepare-deployment, deploy-stratify-api]
        if: ${{ always() && needs.prepare-deployment.outputs.is_stratify_ui_changed == 'true' && needs.deploy-stratify-api.result != 'failure' }}
        environment: Production
        permissions:
            contents: read
            packages: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.release_tag }}

            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Check if image exists in GHCR
              id: image_check
              run: |
                  IMAGE_NAME="ghcr.io/kishanj22/stratify/stratify-ui:${{ needs.prepare-deployment.outputs.stratify_ui_version }}"
                  echo "Checking if image exists: $IMAGE_NAME"

                  if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
                      echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
                      echo "Image exists: $IMAGE_NAME"
                  else
                      echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
                      echo "Image does not exist: $IMAGE_NAME"
                      exit 1
                  fi[]===

            - name: Update Stratify UI in Coolify
              run: |
                  curl -X PATCH "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_UI_UUID }}" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      -d `{
                          "docker_registry_image_tag": "${{ needs.prepare-deployment.outputs.stratify_ui_version }}",
                          "description": "${{ needs.prepare-deployment.outputs.release-tag }}"    
                      }`

            - name: Restart Stratify UI in Coolify
              run: |
                  curl -X GET "${{ secrets.COOLIFY_URL }}/api/v1/applications/${{ secrets.STRATIFY_UI_UUID }}/restart" \
                      -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
                      -H "Content-Type: application/json"
